name: Deploy css_advanced to GitHub Pages

on:
  push:
    branches:
      - main  # or the branch you are using

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./css_advanced  # The directory you want to deploy

